In [1]:
import numpy as np

In [242]:
def read_grid_text(file):
    c = np.loadtxt(file, dtype=str)
    c = np.array([list(d) for d in c])
    return c

In [243]:
def read_target_list(file):
    return np.loadtxt(file, dtype=str).tolist()

In [220]:
# test_array = np.array([['f', 'l', 'p', 'l'],
#                        ['r', 'a', 'o', 'a'],
#                        ['b', 'o', 'd', 'o'],
#                        ['m', 'o', 'v', 'u']])

In [249]:
test_array = read_grid_text(r'/content/drive/My Drive/Colab Notebooks/WordSearchTesting/wordsearch_test1_grid.txt')

In [251]:
print(test_array)

[['C' 'T' 'Y' 'S' 'T' 'R' 'A' 'S' 'C' 'E' 'P' 'L' 'T' 'Y']
 ['O' 'E' 'T' 'C' 'W' 'O' 'L' 'Y' 'I' 'L' 'A' 'S' 'E' 'T']
 ['L' 'A' 'K' 'H' 'L' 'B' 'D' 'E' 'L' 'N' 'T' 'N' 'Y' 'Y']
 ['H' 'C' 'T' 'E' 'L' 'I' 'R' 'D' 'Y' 'I' 'R' 'R' 'Y' 'A']
 ['H' 'H' 'R' 'R' 'A' 'N' 'I' 'R' 'H' 'A' 'L' 'I' 'E' 'B']
 ['N' 'E' 'A' 'B' 'H' 'Y' 'N' 'I' 'B' 'N' 'Y' 'B' 'A' 'N']
 ['N' 'R' 'M' 'A' 'S' 'M' 'A' 'N' 'H' 'A' 'T' 'T' 'A' 'N']
 ['E' 'E' 'P' 'T' 'R' 'A' 'E' 'M' 'E' 'B' 'R' 'A' 'L' 'S']
 ['R' 'K' 'S' 'S' 'A' 'I' 'M' 'O' 'S' 'B' 'Y' 'E' 'A' 'T']
 ['R' 'R' 'T' 'K' 'M' 'K' 'N' 'S' 'C' 'R' 'R' 'A' 'W' 'T']
 ['A' 'E' 'A' 'Y' 'I' 'D' 'B' 'N' 'B' 'D' 'C' 'B' 'Y' 'T']
 ['I' 'L' 'M' 'Y' 'A' 'R' 'A' 'P' 'O' 'E' 'R' 'E' 'E' 'T']
 ['N' 'A' 'P' 'E' 'A' 'P' 'E' 'A' 'P' 'T' 'M' 'Y' 'R' 'N']
 ['O' 'Y' 'R' 'P' 'B' 'C' 'E' 'T' 'A' 'L' 'A' 'L' 'N' 'I']]


In [222]:
# test_seqs = ['lao', 'rad', 'rao', 'pod', 'bod']

In [250]:
test_seqs = read_target_list(r'/content/drive/My Drive/Colab Notebooks/WordSearchTesting/wordsearch_test1_words.txt')

In [252]:
print(test_seqs)

['MANHATTAN', 'TED', 'MOSBY', 'MARSHALL', 'ERIKSEN', 'ROBIN', 'SCHERBATSKY', 'LILY', 'ALDRIN', 'BARNEY', 'LAWYER', 'TEACHER', 'TRAMPSTAMP']


In [254]:
W,H = test_array.shape
print(W,H)

14 14


In [255]:
index_array = np.arange(0, len(test_array.ravel()), 1, dtype=np.uint8).reshape((W,H))

In [256]:
print(index_array)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13]
 [ 14  15  16  17  18  19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36  37  38  39  40  41]
 [ 42  43  44  45  46  47  48  49  50  51  52  53  54  55]
 [ 56  57  58  59  60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95  96  97]
 [ 98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125]
 [126 127 128 129 130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160 161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177 178 179 180 181]
 [182 183 184 185 186 187 188 189 190 191 192 193 194 195]]


In [257]:
flat_test_array = test_array.ravel()
print(flat_test_array)

['C' 'T' 'Y' 'S' 'T' 'R' 'A' 'S' 'C' 'E' 'P' 'L' 'T' 'Y' 'O' 'E' 'T' 'C'
 'W' 'O' 'L' 'Y' 'I' 'L' 'A' 'S' 'E' 'T' 'L' 'A' 'K' 'H' 'L' 'B' 'D' 'E'
 'L' 'N' 'T' 'N' 'Y' 'Y' 'H' 'C' 'T' 'E' 'L' 'I' 'R' 'D' 'Y' 'I' 'R' 'R'
 'Y' 'A' 'H' 'H' 'R' 'R' 'A' 'N' 'I' 'R' 'H' 'A' 'L' 'I' 'E' 'B' 'N' 'E'
 'A' 'B' 'H' 'Y' 'N' 'I' 'B' 'N' 'Y' 'B' 'A' 'N' 'N' 'R' 'M' 'A' 'S' 'M'
 'A' 'N' 'H' 'A' 'T' 'T' 'A' 'N' 'E' 'E' 'P' 'T' 'R' 'A' 'E' 'M' 'E' 'B'
 'R' 'A' 'L' 'S' 'R' 'K' 'S' 'S' 'A' 'I' 'M' 'O' 'S' 'B' 'Y' 'E' 'A' 'T'
 'R' 'R' 'T' 'K' 'M' 'K' 'N' 'S' 'C' 'R' 'R' 'A' 'W' 'T' 'A' 'E' 'A' 'Y'
 'I' 'D' 'B' 'N' 'B' 'D' 'C' 'B' 'Y' 'T' 'I' 'L' 'M' 'Y' 'A' 'R' 'A' 'P'
 'O' 'E' 'R' 'E' 'E' 'T' 'N' 'A' 'P' 'E' 'A' 'P' 'E' 'A' 'P' 'T' 'M' 'Y'
 'R' 'N' 'O' 'Y' 'R' 'P' 'B' 'C' 'E' 'T' 'A' 'L' 'A' 'L' 'N' 'I']


In [258]:
def get_letter(flat_arr, index_arr, posx, posy):
  return flat_arr[index_arr[posx][posy]]

In [259]:
print(get_letter(flat_test_array, index_array, 0, 1))

T


In [277]:
def get_neighbors(x, y, W=W, H=H, index_arr=index_array):
  wlim = W - 1
  hlim = H - 1
  n1x, n1y = max((x - 1),0),  max((y - 1), 0)
  n2x, n2y = max((x - 1),0),      (y + 0)
  n3x, n3y = max((x - 1),0),  min((y + 1), wlim)
  n4x, n4y =     (x + 0),     max((y - 1), 0)
  n5x, n5y =     (x + 0),     min((y + 1), wlim)
  n6x, n6y = min((x + 1), hlim), max((y - 1), 0)
  n7x, n7y = min((x + 1), hlim),     (y + 0)
  n8x, n8y = min((x + 1), hlim), min((y + 1), wlim)
  
  neighbors = [index_arr[n1x, n1y], index_arr[n2x, n2y], index_arr[n3x, n3y],
               index_arr[n4x, n4y],                      index_arr[n5x, n5y],
               index_arr[n6x, n6y], index_arr[n7x, n7y], index_arr[n8x, n8y]]
  neighbors = set(neighbors)
  p = index_arr[x, y]
  try:
    neighbors.remove(p)
    return neighbors
  except:
    return neighbors


In [272]:
neighbors = get_neighbors(0, 2)
print(neighbors)

{1, 2, 3, 15, 16, 17}
2
{1, 3, 15, 16, 17}


In [273]:
for n in neighbors:
  print(n, n // W, n % W)
  print(test_array[n // W][n % W])
  print(flat_test_array[n])

1 0 1
T
T
3 0 3
S
S
15 1 1
E
E
16 1 2
T
T
17 1 3
C
C


In [263]:
def getXY(ind, W=W):
  return ind // W, ind % W

In [264]:
seq = list(test_seqs[0])
print(seq)

['M', 'A', 'N', 'H', 'A', 'T', 'T', 'A', 'N']


In [265]:
first_letter_positions = index_array[np.where(test_array == seq[0])]
print(first_letter_positions)

[ 86  89 105 118 130 156 178]


In [266]:
def getContinuingSeq(spos, epos, seq, ind_arr=index_array, W=W, H=H):
  (x1, x0), (y1, y0) = list(zip(epos, spos))
  v = (x1 - x0, y1 - y0)
  new_seq_pos = []
  for i in range(len(seq)):
    new_seq_pos.append([spos[0] + v[0]*i, spos[1] + v[1]*i])
  return new_seq_pos

In [267]:
pot_seq = getContinuingSeq((0,1), (0,0), seq)

In [268]:
def getLetters(seq, letter_arr=test_array):
  letters = [letter_arr[posx, posy] for posx, posy in seq]
  return letters

In [269]:
def getIndices(seq, index_arr=index_array):
  indices = [index_arr[posx, posy] for posx, posy in seq]
  return indices

In [278]:
for s in first_letter_positions:
  x0,y0 = getXY(s)
  neighbors = get_neighbors(x0,y0)
  for n in neighbors:
    x,y = getXY(n)
    pot_seq_pos = getContinuingSeq((x0,y0), (x,y), seq)
    if all(item >= 0 and item < W and item < H for sublist in pot_seq_pos for item in sublist):
      pot_seq = getLetters(pot_seq_pos)
      if pot_seq == seq:
        matched_seq = pot_seq
        matched_seq_indices = getIndices(pot_seq_pos)
        print(pot_seq_pos)
        print(matched_seq)
        print(matched_seq_indices)

[[6, 5], [6, 6], [6, 7], [6, 8], [6, 9], [6, 10], [6, 11], [6, 12], [6, 13]]
['M', 'A', 'N', 'H', 'A', 'T', 'T', 'A', 'N']
[89, 90, 91, 92, 93, 94, 95, 96, 97]


In [282]:
for seq in test_seqs:
  seq = list(seq)
  first_letter_positions = index_array[np.where(test_array == seq[0])]
  for s in first_letter_positions:
    x0,y0 = getXY(s)
    neighbors = get_neighbors(x0,y0)
    for n in neighbors:
      x,y = getXY(n)
      pot_seq_pos = getContinuingSeq((x0,y0), (x,y), seq)
      if all(item >= 0 and item < W and item < H for sublist in pot_seq_pos for item in sublist):
        pot_seq = getLetters(pot_seq_pos)
        if pot_seq == seq:
          matched_seq = pot_seq
          matched_seq_indices = getIndices(pot_seq_pos)
          print(pot_seq_pos)
          print(matched_seq)
          print(matched_seq_indices)

[[6, 5], [6, 6], [6, 7], [6, 8], [6, 9], [6, 10], [6, 11], [6, 12], [6, 13]]
['M', 'A', 'N', 'H', 'A', 'T', 'T', 'A', 'N']
[89, 90, 91, 92, 93, 94, 95, 96, 97]
[[12, 9], [11, 9], [10, 9]]
['T', 'E', 'D']
[177, 163, 149]
[[8, 6], [8, 7], [8, 8], [8, 9], [8, 10]]
['M', 'O', 'S', 'B', 'Y']
[118, 119, 120, 121, 122]
[[9, 4], [8, 4], [7, 4], [6, 4], [5, 4], [4, 4], [3, 4], [2, 4]]
['M', 'A', 'R', 'S', 'H', 'A', 'L', 'L']
[130, 116, 102, 88, 74, 60, 46, 32]
[[12, 6], [11, 5], [10, 4], [9, 3], [8, 2], [7, 1], [6, 0]]
['E', 'R', 'I', 'K', 'S', 'E', 'N']
[174, 159, 144, 129, 114, 99, 84]
[[0, 5], [1, 5], [2, 5], [3, 5], [4, 5]]
['R', 'O', 'B', 'I', 'N']
[5, 19, 33, 47, 61]
[[0, 3], [1, 3], [2, 3], [3, 3], [4, 3], [5, 3], [6, 3], [7, 3], [8, 3], [9, 3], [10, 3]]
['S', 'C', 'H', 'E', 'R', 'B', 'A', 'T', 'S', 'K', 'Y']
[3, 17, 31, 45, 59, 73, 87, 101, 115, 129, 143]
[[4, 10], [3, 9], [2, 8], [1, 7]]
['L', 'I', 'L', 'Y']
[66, 51, 36, 21]
[[0, 6], [1, 6], [2, 6], [3, 6], [4, 6], [5, 6]]
['A', 'L', '